author: meta1203
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.meta1203.plugins.gpextras.Gpextras
name: GPExtras
startup: postworld
url: http://www.kruxkraft.com/
version: '0.1'
